### PR TITLE
Add py.typed to enable typing

### PR DESCRIPTION
**Pull request by kevinastone**
PEP-561 requires a `py.typed` marker file in the package root to indicate typing information is provided in the package.

More information in the pep: https://www.python.org/dev/peps/pep-0561/#packaging-type-information

## What do these changes do?

The current release of this back port doesn't resolve typing information, resulting in `mypy` errors such as:

```
 error: Untyped decorator makes function "my_example_property" untyped
```

## Checklist

- [X] I think the code is well written
- [X] Unit tests for the changes exist
- [X] Documentation reflects the changes

### CODE REVIEW

**Comment by rggjan** [comment]
What's the status of this? Can it be merged?

**Comment by penguinolog** [comment]
we can not add `py.typed` to backports due to package specific: in backports may be installed more packages (it's namespace package), and not of them are typed

**Comment by kevinastone** [comment]
I didn't know it was a namespace.  I can just move the `py.typed` marker to the sub-module:

> For namespace packages (see PEP 420), the py.typed file should be in the submodules of the namespace, to avoid conflicts and for clarity.

https://www.python.org/dev/peps/pep-0561/#packaging-type-information

**Comment by mara004** [comment]
I doubt if namespace packages are a good idea... Using regular packages seems cleaner

**Pull request merged**
